const FM_SB_URL='https://cxaoomvagqpuatlfthlx.supabase.co';
const FM_SB_KEY='sb_publishable_ud3RGvS6BIe03XJzMZIOSQ_h_QrULbF';
const FM_SESSION_KEY='kobayashi_pms_session_v1';
const FM_MONTH_KEY='kobayashi_pms_finance_month';
let fmRendering=false;

function fmSession(){try{return JSON.parse(localStorage.getItem(FM_SESSION_KEY)||'null')}catch{return null}}
function fmYen(n){return new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0)}
function fmEsc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmTokyoMonth(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit'}).formatToParts(new Date());return `${p.find(x=>x.type==='year')?.value}-${p.find(x=>x.type==='month')?.value}`}
function fmSelectedMonth(){const v=localStorage.getItem(FM_MONTH_KEY);return /^20\d{2}-(0[1-9]|1[0-2])$/.test(v||'')?v:fmTokyoMonth()}
function fmSetMonth(v){if(/^20\d{2}-(0[1-9]|1[0-2])$/.test(v||'')){localStorage.setItem(FM_MONTH_KEY,v);window.dispatchEvent(new CustomEvent('pms-finance-month-change',{detail:{month:v}}))}}
function fmShift(v,d){const [y,m]=v.split('-').map(Number),dt=new Date(Date.UTC(y,m-1+d,1));return `${dt.getUTCFullYear()}-${String(dt.getUTCMonth()+1).padStart(2,'0')}`}
function fmBounds(v){const [y,m]=v.split('-').map(Number),a=`${y}-${String(m).padStart(2,'0')}-01`,ny=m===12?y+1:y,nm=m===12?1:m+1,b=`${ny}-${String(nm).padStart(2,'0')}-01`;return {a,b,label:`${y}年${m}月`}}
async function fmRaw(path,{method='GET',body,headers={}}={}){const s=fmSession();if(!s?.access_token)throw new Error('请先登录');const h={apikey:FM_SB_KEY,Authorization:`Bearer ${s.access_token}`,...headers};if(body!==undefined){h['Content-Type']='application/json';body=JSON.stringify(body)}const r=await fetch(FM_SB_URL+path,{method,headers:h,body});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.error_description||data?.error||`HTTP ${r.status}`);return data}
async function fmOrg(){const u=await fmRaw('/auth/v1/user');const x=await fmRaw(`/rest/v1/memberships?select=organization_id,role,can_view_financials&user_id=eq.${encodeURIComponent(u.id)}&limit=1`);return x?.[0]||null}

async function fmFetch(orgId,month){const {a,b,label}=fmBounds(month);const qOrg=encodeURIComponent(orgId);const [r,c,e,inv,items]=await Promise.all([
 fmRaw(`/rest/v1/reservations?select=gross_amount_yen,platform_fee_yen,status&organization_id=eq.${qOrg}&check_in=gte.${a}&check_in=lt.${b}&status=neq.cancelled`),
 fmRaw(`/rest/v1/cleaning_cost_entries?select=id,unit_id,checkout_date,expected_amount_yen,excluded&organization_id=eq.${qOrg}&checkout_date=gte.${a}&checkout_date=lt.${b}`),
 fmRaw(`/rest/v1/expense_transactions?select=id,category,amount_yen,occurred_on,note&organization_id=eq.${qOrg}&occurred_on=gte.${a}&occurred_on=lt.${b}&order=occurred_on.desc`),
 fmRaw(`/rest/v1/vendor_invoices?select=id,vendor_id,total_amount_yen,status,invoice_number,source_file_name,parse_status,cleaning_vendors(name)&organization_id=eq.${qOrg}&invoice_month=eq.${a}`),
 fmRaw(`/rest/v1/vendor_invoice_items?select=id,invoice_id,actual_amount_yen,basic_cleaning_yen,laundry_yen,supplies_yen,garbage_yen,transport_yen,vendor_invoices!inner(organization_id,invoice_month)&vendor_invoices.organization_id=eq.${qOrg}&vendor_invoices.invoice_month=eq.${a}`)
 ]);
 const reservations=r||[],cleaning=(c||[]).filter(x=>!x.excluded),expenses=e||[],invoices=inv||[],rows=items||[];
 const gross=reservations.reduce((s,x)=>s+(x.gross_amount_yen||0),0),fees=reservations.reduce((s,x)=>s+(x.platform_fee_yen||0),0),expectedBasic=cleaning.reduce((s,x)=>s+(x.expected_amount_yen||0),0),other=expenses.reduce((s,x)=>s+(x.amount_yen||0),0),actualTotal=invoices.reduce((s,x)=>s+(x.total_amount_yen||0),0);
 const actualBasic=rows.reduce((s,x)=>s+(x.basic_cleaning_yen||0),0),laundry=rows.reduce((s,x)=>s+(x.laundry_yen||0),0),supplies=rows.reduce((s,x)=>s+(x.supplies_yen||0),0),garbage=rows.reduce((s,x)=>s+(x.garbage_yen||0),0),transport=rows.reduce((s,x)=>s+(x.transport_yen||0),0),parsedTotal=rows.reduce((s,x)=>s+(x.actual_amount_yen||0),0),undistributed=Math.max(0,actualTotal-parsedTotal),hasActual=invoices.length>0,hasBreakdown=rows.length>0;
 return {a,b,label,reservations,cleaning,expenses,invoices,rows,gross,fees,expectedBasic,other,actualTotal,actualBasic,laundry,supplies,garbage,transport,parsedTotal,undistributed,hasActual,hasBreakdown,projected:gross-fees-expectedBasic-other,actualProfit:gross-fees-(hasActual?actualTotal:expectedBasic)-other};
}

function fmStyles(){if(document.querySelector('#fmStyles'))return;const s=document.createElement('style');s.id='fmStyles';s.textContent=`.fm-nav{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:16px}.fm-nav input{min-height:38px;border:1px solid #dfe3eb;border-radius:10px;padding:0 10px;background:#fff}.fm-note{font-size:13px;color:#6b7280;line-height:1.6;margin:0 0 12px}.fm-breakdown .row strong{font-variant-numeric:tabular-nums}.fm-month-tag{font-weight:700}.fm-expenses{max-height:320px;overflow:auto}.fm-warning{padding:12px 14px;border-radius:12px;background:#fff7ed;color:#9a3412;margin:12px 0;border:1px solid #fed7aa}.fm-warning .actions{margin-top:10px;display:flex;gap:8px;flex-wrap:wrap}`;document.head.appendChild(s)}

async function renderFinanceMonth(force=false){const title=document.querySelector('#pageTitle'),content=document.querySelector('#content');if(!title||!content||title.textContent.trim()!=='财务'||fmRendering)return;const month=fmSelectedMonth();if(!force&&content.dataset.fmDone==='1'&&content.dataset.fmMonth===month)return;fmRendering=true;fmStyles();content.dataset.fmMonth=month;content.dataset.fmDone='0';content.innerHTML='<section class="panel"><div class="empty">正在读取所选月份的财务数据…</div></section>';
 try{const mem=await fmOrg();if(!mem?.can_view_financials)throw new Error('这个账号没有财务查看权限');const d=await fmFetch(mem.organization_id,month);const basicDiff=d.actualBasic-d.expectedBasic;const breakdownText=d.hasBreakdown?fmYen(d.actualBasic):'明细未拆分';
 content.innerHTML=`<div class="fm-nav"><button class="btn" id="fmPrev">← 上个月</button><input id="fmMonth" type="month" value="${month}"><button class="btn" id="fmNext">下个月 →</button><span class="fm-month-tag">${d.label}</span></div>
 <div class="metrics"><div class="card metric"><label>住宿收入</label><strong>${fmYen(d.gross)}</strong><small>${d.reservations.length} 笔有效订单</small></div><div class="card metric"><label>平台手续费</label><strong>${fmYen(d.fees)}</strong><small>订单渠道成本</small></div><div class="card metric"><label>预计基础清扫费</label><strong>${fmYen(d.expectedBasic)}</strong><small>按退房日自动计算</small></div><div class="card metric emphasis"><label>${d.hasActual?'实际净利润':'预计净利润'}</label><strong>${fmYen(d.actualProfit)}</strong><small>${d.hasActual?'已使用業者实际总账单':'尚未收到清扫账单'}</small></div></div>
 <section class="panel fm-breakdown"><div class="panel-head"><div><span class="eyebrow">CLEANING COST</span><h2>清扫成本对比</h2></div></div><p class="fm-note">系统预计只和 PDF 的「基本清扫料金」比较；实际净利润使用清扫業者账单总金额，包含洗衣、备品、垃圾回收和交通费。</p><div class="row"><span>系统预计基础清扫费</span><strong>${fmYen(d.expectedBasic)}</strong></div><div class="row"><span>实际基础清扫费</span><strong>${breakdownText}</strong></div><div class="row"><span>基础清扫差额</span><strong>${d.hasBreakdown?fmYen(basicDiff):'—'}</strong></div><div class="row"><span>＋ ランドリー</span><strong>${d.hasBreakdown?fmYen(d.laundry):'—'}</strong></div><div class="row"><span>＋ 备品</span><strong>${d.hasBreakdown?fmYen(d.supplies):'—'}</strong></div><div class="row"><span>＋ 垃圾回收</span><strong>${d.hasBreakdown?fmYen(d.garbage):'—'}</strong></div><div class="row"><span>＋ 交通费</span><strong>${d.hasBreakdown?fmYen(d.transport):'—'}</strong></div>${d.undistributed>0?`<div class="row"><span>＋ 未拆分账单金额</span><strong>${fmYen(d.undistributed)}</strong></div>`:''}<div class="row"><span><strong>实际清扫相关总成本</strong></span><strong>${d.hasActual?fmYen(d.actualTotal):'未收到'}</strong></div></section>
 <div class="grid2"><section class="panel"><div class="panel-head"><div><span class="eyebrow">CLEANING INVOICE</span><h2>清扫業者账单</h2></div><div class="panel-head-actions"><button class="btn small" id="fmManualInvoice">＋ 手动录入</button></div></div>${d.invoices.length?d.invoices.map(x=>`<div class="row"><div><strong>${fmEsc(x.cleaning_vendors?.name||'清扫業者')}</strong><br><small>${x.source_file_name?`PDF · ${fmEsc(x.source_file_name)}`:(x.invoice_number?`账单 ${fmEsc(x.invoice_number)}`:'手动录入')}</small></div><strong>${fmYen(x.total_amount_yen)}</strong></div>`).join(''):'<div class="empty">这个月还没有清扫账单</div>'}</section><section class="panel"><div class="panel-head"><div><span class="eyebrow">EXPENSES</span><h2>其他支出</h2></div><button class="btn small" id="fmAddExpense">＋ 新增</button></div><div class="fm-expenses">${d.expenses.length?d.expenses.map(x=>`<div class="row"><div><strong>${fmEsc(x.category)}</strong><br><small>${x.occurred_on}${x.note?` · ${fmEsc(x.note)}`:''}</small></div><strong>${fmYen(x.amount_yen)}</strong></div>`).join(''):'<div class="empty">这个月还没有其他支出</div>'}</div></section></div>
 <section class="panel"><div class="panel-head"><div><span class="eyebrow">PROFIT</span><h2>利润构成</h2></div></div><div class="row"><span>住宿收入</span><strong>${fmYen(d.gross)}</strong></div><div class="row"><span>－ 平台手续费</span><strong>${fmYen(d.fees)}</strong></div><div class="row"><span>－ 预计基础清扫费</span><strong>${fmYen(d.expectedBasic)}</strong></div>${d.hasActual?`<div class="row"><span>－ 实际清扫相关总成本</span><strong>${fmYen(d.actualTotal)}</strong></div>`:''}<div class="row"><span>－ 其他支出</span><strong>${fmYen(d.other)}</strong></div><div class="row"><span>预计净利润</span><strong>${fmYen(d.projected)}</strong></div>${d.hasActual?`<div class="row"><span><strong>实际净利润</strong></span><strong>${fmYen(d.actualProfit)}</strong></div>`:''}</section>`;
 content.dataset.fmDone='1';
 document.querySelector('#fmPrev').onclick=()=>{fmSetMonth(fmShift(month,-1));renderFinanceMonth(true)};document.querySelector('#fmNext').onclick=()=>{fmSetMonth(fmShift(month,1));renderFinanceMonth(true)};document.querySelector('#fmMonth').onchange=e=>{if(e.target.value){fmSetMonth(e.target.value);renderFinanceMonth(true)}};document.querySelector('#fmAddExpense').onclick=()=>fmAddExpense(mem.organization_id,month);document.querySelector('#fmManualInvoice').onclick=()=>fmManualInvoice(mem.organization_id,d.a,month);
 }catch(err){content.innerHTML=`<section class="panel"><div class="message error">${fmEsc(err.message)}</div></section>`;content.dataset.fmDone='1'}finally{fmRendering=false}}

async function fmAddExpense(orgId,month){const category=prompt('支出类别（例：耗材、水电、维修、网络）','耗材');if(!category?.trim())return;const amountText=prompt('金额（¥）');if(amountText===null)return;const amount=Number(String(amountText).replace(/,/g,''));if(!Number.isFinite(amount)||amount<0)return alert('金额不正确');const {a}=fmBounds(month);const date=prompt('日期（YYYY-MM-DD）',a);if(!date)return;const note=prompt('备注（可选）','')||null;try{await fmRaw('/rest/v1/expense_transactions',{method:'POST',body:{organization_id:orgId,category:category.trim(),amount_yen:Math.round(amount),occurred_on:date,note},headers:{Prefer:'return=representation'}});await renderFinanceMonth(true)}catch(err){alert(err.message)}}

async function fmManualInvoice(orgId,monthStart,month){const vendor=prompt('清扫業者名称','清掃業者');if(!vendor?.trim())return;const amountText=prompt(`${month} 实际账单总额（¥）`);if(amountText===null)return;const amount=Number(String(amountText).replace(/,/g,''));if(!Number.isFinite(amount)||amount<0)return alert('金额不正确');try{let vs=await fmRaw(`/rest/v1/cleaning_vendors?select=id,name&organization_id=eq.${encodeURIComponent(orgId)}&name=eq.${encodeURIComponent(vendor.trim())}&limit=1`);let vid=vs?.[0]?.id;if(!vid){const x=await fmRaw('/rest/v1/cleaning_vendors',{method:'POST',body:{organization_id:orgId,name:vendor.trim()},headers:{Prefer:'return=representation'}});vid=x?.[0]?.id}await fmRaw('/rest/v1/vendor_invoices?on_conflict=organization_id,vendor_id,invoice_month',{method:'POST',body:{organization_id:orgId,vendor_id:vid,invoice_month:monthStart,total_amount_yen:Math.round(amount),status:'received',parse_status:'manual'},headers:{Prefer:'resolution=merge-duplicates,return=representation'}});await renderFinanceMonth(true)}catch(err){alert(err.message)}}

function guardPdfMonth(){const modal=document.querySelector('#pdfImportModal'),review=document.querySelector('#pdfReview');if(!modal||!review||review.dataset.fmGuarded==='1')return;const strong=review.querySelector('.pdf-kpi strong');const confirmBtn=document.querySelector('#pdfConfirm');if(!strong||!confirmBtn)return;const m=strong.textContent.trim().match(/^(20\d{2})\/(\d{1,2})$/);if(!m)return;const parsed=`${m[1]}-${String(Number(m[2])).padStart(2,'0')}`,selected=fmSelectedMonth();review.dataset.fmGuarded='1';if(parsed===selected)return;confirmBtn.disabled=true;const box=document.createElement('div');box.className='fm-warning';box.innerHTML=`检测到账单月份为 <strong>${m[1]}年${Number(m[2])}月</strong>，但你当前查看的是 <strong>${selected.replace('-', '年')}月</strong>。<br>为了避免把账单记错月份，请先切换。<div class="actions"><button class="btn primary" id="fmPdfSwitch">切换到 ${m[1]}年${Number(m[2])}月并继续</button><button class="btn" id="fmPdfCancel">取消本次导入</button></div>`;review.prepend(box);document.querySelector('#fmPdfSwitch').onclick=()=>{fmSetMonth(parsed);confirmBtn.disabled=false;box.innerHTML=`<strong>✓ 已切换到账单月份：${m[1]}年${Number(m[2])}月</strong>`};document.querySelector('#fmPdfCancel').onclick=()=>modal.remove()}

const fmObs=new MutationObserver(()=>{clearTimeout(window.__fmTimer);window.__fmTimer=setTimeout(()=>{renderFinanceMonth();guardPdfMonth()},100)});fmObs.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('pms-finance-month-change',()=>renderFinanceMonth(true));window.addEventListener('load',()=>setTimeout(()=>renderFinanceMonth(true),500));setTimeout(()=>renderFinanceMonth(true),900);
